// <auto-generated />
using System;
using CodeSprint.Problems.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CodeSprint.Problems.Migrations
{
    [DbContext(typeof(ProblemsDbContext))]
    partial class ProblemsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("problems")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CodeSprint.Problems.Domain.Problem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("difficulty");

                    b.Property<int>("EstimatedMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_minutes");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("_constraints")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("constraints");

                    b.Property<string>("_inputFormat")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("input_format");

                    b.Property<string>("_notes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("notes");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("problems", "problems");
                });

            modelBuilder.Entity("CodeSprint.Problems.Domain.Problem", b =>
                {
                    b.OwnsMany("CodeSprint.Problems.Domain.Example", "Examples", b1 =>
                        {
                            b1.Property<Guid>("problem_id")
                                .HasColumnType("uuid");

                            b1.Property<int>("Ordinal")
                                .HasColumnType("integer")
                                .HasColumnName("ordinal");

                            b1.Property<string>("Explanation")
                                .HasColumnType("text")
                                .HasColumnName("explanation");

                            b1.Property<string>("Input")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("input");

                            b1.Property<string>("Output")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("output");

                            b1.HasKey("problem_id", "Ordinal");

                            b1.ToTable("problem_examples", "problems");

                            b1.WithOwner()
                                .HasForeignKey("problem_id");
                        });

                    b.OwnsMany("CodeSprint.Problems.Domain.Tag", "Tags", b1 =>
                        {
                            b1.Property<Guid>("problem_id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("tag");

                            b1.HasKey("problem_id", "Value");

                            b1.ToTable("problem_tags", "problems");

                            b1.WithOwner()
                                .HasForeignKey("problem_id");
                        });

                    b.OwnsMany("CodeSprint.Problems.Domain.TestCase", "TestCases", b1 =>
                        {
                            b1.Property<Guid>("problem_id")
                                .HasColumnType("uuid");

                            b1.Property<int>("Ordinal")
                                .HasColumnType("integer")
                                .HasColumnName("ordinal");

                            b1.Property<string>("ExpectedOutput")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("expected_output");

                            b1.Property<string>("Input")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("input");

                            b1.Property<bool>("IsHidden")
                                .HasColumnType("boolean")
                                .HasColumnName("is_hidden");

                            b1.HasKey("problem_id", "Ordinal");

                            b1.ToTable("problem_test_cases", "problems");

                            b1.WithOwner()
                                .HasForeignKey("problem_id");
                        });

                    b.Navigation("Examples");

                    b.Navigation("Tags");

                    b.Navigation("TestCases");
                });
#pragma warning restore 612, 618
        }
    }
}
