import type { Problem } from "./types";

export const problems: Problem[] = [
  {
    id: "1",
    title: "Two Sum",
    difficulty: "easy",
    tags: ["Mathematical"],
    solvedCount: 12400,
    estimatedTime: "10 min",
    points: 50,
    status: "review",
  },
  {
    id: "2",
    title: "Valid Parentheses",
    difficulty: "easy",
    tags: ["Strings"],
    solvedCount: 9800,
    estimatedTime: "15 min",
    points: 50,
    status: "continue",
  },
  {
    id: "3",
    title: "Longest Substring Without Repeating Characters",
    difficulty: "medium",
    tags: ["Strings"],
    solvedCount: 7200,
    estimatedTime: "20 min",
    points: 100,
    status: "start",
  },
  {
    id: "4",
    title: "3Sum",
    difficulty: "medium",
    tags: ["Mathematical"],
    solvedCount: 5100,
    estimatedTime: "25 min",
    points: 100,
    status: "start",
  },
  {
    id: "5",
    title: "Median of Two Sorted Arrays",
    difficulty: "hard",
    tags: ["Logical"],
    solvedCount: 2300,
    estimatedTime: "40 min",
    points: 200,
    status: "start",
  },
  {
    id: "6",
    title: "Trapping Rain Water",
    difficulty: "hard",
    tags: ["Geometrics"],
    solvedCount: 1900,
    estimatedTime: "35 min",
    points: 200,
    status: "start",
  },
  {
    id: "7",
    title: "Binary Search",
    difficulty: "easy",
    tags: ["Logical"],
    solvedCount: 11000,
    estimatedTime: "10 min",
    points: 50,
    status: "review",
  },
  {
    id: "8",
    title: "Merge Intervals",
    difficulty: "medium",
    tags: ["Mathematical"],
    solvedCount: 6500,
    estimatedTime: "20 min",
    points: 100,
    status: "start",
  },
  {
    id: "9",
    title: "Word Search",
    difficulty: "medium",
    tags: ["Strings", "Logical"],
    solvedCount: 4800,
    estimatedTime: "30 min",
    points: 100,
    status: "start",
  },
  {
    id: "10",
    title: "Minimum Window Substring",
    difficulty: "hard",
    tags: ["Strings"],
    solvedCount: 1200,
    estimatedTime: "45 min",
    points: 200,
    status: "start",
  },
];
