var builder = DistributedApplication.CreateBuilder(args);

// PostgreSQL server with a persistent data volume and the pgAdmin management UI.
// Credentials are generated by Aspire and injected into referencing projects.
var postgres = builder.AddPostgres("postgres")
    .WithDataVolume("codesprint-pgdata")
    .WithPgAdmin();

// Database for the Users bounded context.
var usersDb = postgres.AddDatabase("usersdb");

// Database for the Problems bounded context.
var problemsDb = postgres.AddDatabase("problemsdb");

// Domain services — internal only, reached through the gateway via service discovery.
var usersApi = builder.AddProject<Projects.CodeSprint_Users>("users-api")
       .WithReference(usersDb)
       .WaitFor(usersDb);

var problemsApi = builder.AddProject<Projects.CodeSprint_Problems>("problems-api")
       .WithReference(problemsDb)
       .WaitFor(problemsDb);

// API gateway — the only public-facing project. References to the services inject the
// discovery config that lets YARP resolve "http://users-api" / "http://problems-api".
builder.AddProject<Projects.CodeSprint_Gateway>("gateway")
       .WithReference(usersApi)
       .WithReference(problemsApi)
       .WaitFor(usersApi)
       .WaitFor(problemsApi)
       .WithExternalHttpEndpoints();

builder.Build().Run();
