var builder = DistributedApplication.CreateBuilder(args);

// PostgreSQL server with a persistent data volume and the pgAdmin management UI.
// Credentials are generated by Aspire and injected into referencing projects.
var postgres = builder.AddPostgres("postgres")
    .WithDataVolume("codesprint-pgdata");

// Database for the Users bounded context.
var usersDb = postgres.AddDatabase("usersdb");

// Database for the Problems bounded context.
var problemsDb = postgres.AddDatabase("problemsdb");

// Database for the Submissions bounded context.
var submissionsDb = postgres.AddDatabase("submissionsdb");

// RabbitMQ broker for cross-context integration events. The management plugin
// exposes the broker's web UI for inspecting exchanges/queues during development.
// Credentials are generated by Aspire and injected into referencing projects via
// the "messaging" connection name (see AddCodeSprintMessaging in ServiceDefaults).
var messaging = builder.AddRabbitMQ("messaging")
    .WithManagementPlugin();

// Domain services — internal only, reached through the gateway via service discovery.
var usersApi = builder.AddProject<Projects.CodeSprint_Users>("users-api")
       .WithReference(usersDb)
       .WithReference(messaging)
       .WaitFor(usersDb)
       .WaitFor(messaging);

var problemsApi = builder.AddProject<Projects.CodeSprint_Problems>("problems-api")
       .WithReference(problemsDb)
       .WaitFor(problemsDb);

// Submissions service — references the Users service so http://users-api resolves
// for the UsersApiClient that maps the caller's sub claim to a UserId.
var submissionsApi = builder.AddProject<Projects.CodeSprint_Submissions>("submissions-api")
       .WithReference(submissionsDb)
       .WithReference(usersApi)
       .WithReference(messaging)
       .WaitFor(submissionsDb)
       .WaitFor(usersApi)
       .WaitFor(messaging);

// API gateway — the only public-facing project. References to the services inject the
// discovery config that lets YARP resolve "http://users-api" / "http://problems-api".
builder.AddProject<Projects.CodeSprint_Gateway>("gateway")
       .WithReference(usersApi)
       .WithReference(problemsApi)
       .WithReference(submissionsApi)
       .WaitFor(usersApi)
       .WaitFor(problemsApi)
       .WaitFor(submissionsApi)
       .WithExternalHttpEndpoints();

builder.Build().Run();
