// <auto-generated />
using System;
using CodeSprint.Submissions.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CodeSprint.Submissions.Migrations
{
    [DbContext(typeof(SubmissionsDbContext))]
    partial class SubmissionsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("submissions")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CodeSprint.Submissions.Domain.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("language");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "SubmittedAt");

                    b.ToTable("submissions", "submissions");
                });

            modelBuilder.Entity("CodeSprint.Submissions.Domain.Submission", b =>
                {
                    b.OwnsOne("CodeSprint.Submissions.Domain.Evaluation", "Evaluation", b1 =>
                        {
                            b1.Property<Guid>("SubmissionId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("EvaluatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("evaluated_at");

                            b1.Property<int>("MemoryKb")
                                .HasColumnType("integer")
                                .HasColumnName("memory_kb");

                            b1.Property<int>("PointsAwarded")
                                .HasColumnType("integer")
                                .HasColumnName("points_awarded");

                            b1.Property<int>("RuntimeMs")
                                .HasColumnType("integer")
                                .HasColumnName("runtime_ms");

                            b1.Property<string>("Verdict")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("verdict");

                            b1.HasKey("SubmissionId");

                            b1.ToTable("submissions", "submissions");

                            b1.WithOwner()
                                .HasForeignKey("SubmissionId");

                            b1.OwnsMany("CodeSprint.Submissions.Domain.TestCaseResult", "Results", b2 =>
                                {
                                    b2.Property<Guid>("submission_id")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Ordinal")
                                        .HasColumnType("integer")
                                        .HasColumnName("ordinal");

                                    b2.Property<string>("ActualOutput")
                                        .HasColumnType("text")
                                        .HasColumnName("actual_output");

                                    b2.Property<bool>("IsHidden")
                                        .HasColumnType("boolean")
                                        .HasColumnName("is_hidden");

                                    b2.Property<int>("MemoryKb")
                                        .HasColumnType("integer")
                                        .HasColumnName("memory_kb");

                                    b2.Property<int>("RuntimeMs")
                                        .HasColumnType("integer")
                                        .HasColumnName("runtime_ms");

                                    b2.Property<string>("Status")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)")
                                        .HasColumnName("status");

                                    b2.HasKey("submission_id", "Ordinal");

                                    b2.ToTable("submission_test_results", "submissions");

                                    b2.WithOwner()
                                        .HasForeignKey("submission_id");
                                });

                            b1.Navigation("Results");
                        });

                    b.Navigation("Evaluation");
                });
#pragma warning restore 612, 618
        }
    }
}
